### PR TITLE
test: assert the right thing on both menu backends, and map the root reliably

### LINKED ISSUE #379: test: six macOS test failures are test defects — backend assumptions + order dependence
## Summary

`python tests/run_gui.py` reports six failures on macOS on a clean `main`. All six
are **test defects, not product bugs** — verified individually. They have been
carried as a hand-maintained "known failing" list in `CLAUDE.md`, which is fragile:
telling a real regression from the accepted noise currently requires diffing
against a prose list in a doc.

Not caused by the 0.1.8 scaling fix — the set is identical before and after.

## Category 1 — assume the Win/Linux menu backend (4 tests)

macOS uses `_NativeContextMenu`; these poke at `_ToplevelContextMenu` internals:

| test | error |
|---|---|
| `test_overlay_container_coverage.py::test_propagate_skips_nested_toplevels` | `AttributeError: '_NativeContextMenu' object has no attribute '_toplevel'` |
| `test_toolbar_menu.py::test_add_menu_builds_model_and_trigger` | `AttributeError: '_NativeContextMenu' object has no attribute '_items'` |
| `test_select_options.py::test_selectbutton_disabled_menu_item` | `IndexError: list index out of range` |
| `test_add_toolbar.py::test_bridge_inactive_on_non_macos` | asserts `not app._menus_are_native()` |

The last is self-documenting: it is named `_non_macos`, asserts non-macOS
behavior, and has no skip guard, so it runs on macOS and fails by construction.

**These are also a coverage hole, not just noise.** They are the only tests for
menu construction and overlay propagation, and on macOS they abort before
asserting anything meaningful — so the macOS native-menu path is effectively
untested while appearing tested.

Fix: guard or parametrize by backend so each platform asserts the right thing,
rather than skipping on macOS (a skip would preserve the coverage hole).

## Category 2 — order-dependent (2 tests)

- `test_pagestack.py::test_visited_pages_stay_mapped_on_macos`
- `test_pagestack.py::test_return_after_many_visits_does_not_remap_on_macos`

Both **pass in isolation** (`4 passed` for the file) and fail only in the full
shared-root run. State pollution from an earlier test. Needs the polluting test
identified and the leaked state reset in a fixture.

## Why this is worth clearing

A permanently red baseline is how the recent Tk 9 bugs stayed invisible. Verifying
the 0.1.8 fix required diffing the failure set against the prose list in
`CLAUDE.md` to establish "no regressions" — that works only while the list stays
accurate and someone remembers to check it. A seventh failure would blend in.

See also #378 (the suite cannot complete at all under Tk 9) and #380 (no CI test
workflow), which compound this: nothing is watching automatically.

## Reproduce

```
python tests/run_gui.py          # macOS; 6 failures
python -m pytest tests/widgets/public/test_pagestack.py -q   # 4 passed — order-dependent
```

### PR DESCRIPTION
**Pull request by israel-dryer**
Closes #379.

Six failures on macOS on a clean `main`, none of them a product bug.

## 🍎 Instructions for the macOS tester

I develop on Windows + Tk 8.6, where these six tests **already passed** — that is
the whole problem. The fixes are written against measured backend behavior (see
below), but **the failing-to-passing transition can only be observed on macOS.**

**1. Confirm the six failures are gone.**

```bash
python tests/run_gui.py
```

Expect **0 failures**. Before this branch, `main` gives six:

| test | was |
|---|---|
| `test_add_toolbar.py::test_bridge_inactive_on_non_macos` | assert `not _menus_are_native()` |
| `test_toolbar_menu.py::test_add_menu_builds_model_and_trigger` | `AttributeError: _items` |
| `test_overlay_container_coverage.py::test_propagate_skips_nested_toplevels` | `AttributeError: _toplevel` |
| `test_select_options.py::test_selectbutton_disabled_menu_item` | `IndexError` |
| `test_pagestack.py::test_visited_pages_stay_mapped_on_macos` | order-dependent |
| `test_pagestack.py::test_return_after_many_visits_does_not_remap_on_macos` | order-dependent |

Note the first one is **renamed** to `test_bridge_state_matches_the_platform`,
so don't look for the old name.

**2. Confirm the macOS branches actually execute** — the ones I could not reach.
On macOS these should now take the *native* path:

```bash
python -m pytest tests/widgets/public/test_menu_backend_probe.py -v
```

All 10 must pass. `test_platform_flag_matches_the_backend_contextmenu_picks` is
the one that proves it: on macOS it asserts `is_native(...) is True`, on Windows
`is False`. If that passes on your machine, the probe is reading the real
NSMenu-backed backend.

**3. Confirm the PageStack fix is the right diagnosis** — this is the one I am
least sure of. Run the two tests **alone**, then in the full run:

```bash
python -m pytest tests/widgets/public/test_pagestack.py -q          # passed before too
python tests/run_gui.py                                             # the real check
```

My hypothesis: `shown_app` called `deiconify()` then `update_idletasks()`, which
does **not** process the map event — it only runs idle callbacks — so whether the
root was really mapped depended on what was queued ahead of it. The fixture now
pumps `update()` until the root reports mapped.

If they **still** fail, the new precondition assertion tells you which half is
wrong:
- `AssertionError: shown_app did not map the root` → my diagnosis is right but
  the pump is insufficient; the root genuinely is not mapping. Raise the bound or
  add `wait_visibility`.
- the original `pages[...].winfo_ismapped()` assertion → the root *is* mapped and
  the pollution is elsewhere. Please bisect with `-p no:randomly` and post the
  preceding test; I'll chase it from there.

**4. Sanity-check the menus by hand**, since no test asserts appearance: open
`python -m bootstack` (the bundled demo), confirm the menu bar still populates
the macOS global bar and that a right-click context menu still opens.

---

### Four backend-assuming tests

`ContextMenu` picks its implementation from the windowing system —
`_ToplevelContextMenu` (themed widgets in an overrideredirect Toplevel)
everywhere, `_NativeContextMenu` (a real `tk.Menu`/NSMenu) on macOS. They share
no internals, and four tests reached straight into the themed one's `_items` /
`_toplevel`.

**These were a coverage hole, not just noise.** They are the only tests for menu
construction and overlay propagation, and on macOS they raised before asserting
anything — so that path was untested while appearing tested. A `skipif` would
have kept the hole, so the tests now read through two new fixtures in
`tests/conftest.py`:

- `menu_probe` — `is_native` / `item_count` / `item_disabled` / `popup_toplevel`,
  each reading whichever backend it is handed.
- `menus_are_native` — the same `tk windowingsystem == 'aqua'` check
  `ChromeHostMixin._menus_are_native` makes.

`test_bridge_inactive_on_non_macos` was the clearest case: named `_non_macos`,
asserting non-macOS behavior, with no guard, so it ran on macOS and failed by
construction. It is now `test_bridge_state_matches_the_platform` and asserts
against the platform rather than one of the two answers — on macOS that the menu
is bridged and the in-window trigger is *not* mapped.

### Verifying the macOS branch from Windows

The probe is load-bearing on a platform most contributors cannot run, so this is
not left to trust. `tests/widgets/public/test_menu_backend_probe.py` (10 tests)
drives **both backend classes directly** instead of whichever the platform
selects — a `tk.Menu` is real on every platform; only the *choice* is
platform-specific. So the native branch is exercised on Windows and Linux too.

Measured on Windows before writing the helper, rather than assumed:

| | themed | native |
|---|---|---|
| `_items` | ✅ dict of Buttons, `.state()` | ❌ |
| `_toplevel` | ✅ | ❌ |
| `_menu` | ❌ | ✅ `tk.Menu` |
| item count | `len(_items)` = 3 | `index('end')` = 2 → **3** |
| disabled item | `('disabled',)` | `'disabled'` |

The empty-menu case is covered too — `tk.Menu.index('end')` returns `None`, not
`-1`, and reading that wrong would report 1 entry for an empty native menu.

### Two order-dependent PageStack tests

Covered under tester instruction 3 above.

### One test strengthened

`test_propagate_skips_nested_toplevels` reached for the popup Toplevel by hand.
It now asserts the walk **actually ran** (without which the rest passes on a walk
that did nothing) and checks *every* nested Toplevel. I verified on Windows that
the popup really is a descendant of the target, so the loop finds it rather than
silently iterating nothing.

## Verification

- `python tests/run_gui.py` on Windows + Tk 8.6: **795 passed**, all legs green,
  exit 0 (766 before this branch's 10 new tests + the 19 merged in #382).
- No product code changed — tests and `conftest.py` only.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by israel-dryer** [comment]
Pushed two review fixes after a pass over the final diff. Both were the same
cross-platform split these helpers exist to remove — and both were latent macOS
breakage in the *test infrastructure* I was adding.

**1. `item_disabled` raised `TclError` on a separator, on the native backend
only.** The themed backend answers `False`; asked for a separator's state, a
`tk.Menu` raises `unknown option "-state"`. So the helper would have answered on
Windows and Linux and blown up on macOS. Normalized: a separator is never
disabled, on both.

**2. `is_native` duck-typed on `hasattr(_menu) and not hasattr(_items)`.** The
negative half is fragile — giving the native backend an `_items` attribute for
parity would silently route every macOS test down the *themed* branch and the
failures would be baffling. Now an `isinstance` check.

**Separator coverage added** (6 more tests, 16 total in the probe file). This
matters specifically for macOS: `test_add_menu_builds_model_and_trigger` asserts
a count of **3** for a menu containing a separator, so the two backends agreeing
that a separator counts as an entry is load-bearing there — and was untested.
Measured on both backends:

```
themed   count=3  disabled_by_index=[False, False, True]
native   count=3  disabled_by_index=[False, TclError, True]   <-- the bug
```

Count and index alignment agree; only the separator's state differed.

I confirmed the new test is not vacuous by removing the normalization and
re-running — `test_separator_is_never_disabled[native]` fails with the exact
`TclError` that would have hit you on macOS.

Full suite on Windows + Tk 8.6: **801 passed**, all legs green, exit 0.

The tester instructions in the PR description are unchanged and still apply.

**Comment by israel-dryer** [comment]
## 🍎 macOS run — done, plus two corrections to the body above

**Environment:** macOS 26.5.2, Tk 8.6, Python 3.14.0, editable install.

**Baseline on `main` first**, so the transition was observed rather than assumed:
`6 failed, 825 passed` — exactly the six listed. Then on this branch as originally
pushed: **`4 failed, 843 passed`**. Two of the six were fixed; four were not.
Both causes are now fixed in 5ad14cc1 and the suite is green:

```
$ python tests/run_gui.py
All GUI test legs passed.     # exit 0
```

Tester step 2 passed as written — `test_menu_backend_probe.py` is fully green and
`test_platform_flag_matches_the_backend_contextmenu_picks` asserts `is_native(...)
is True` here, so the probe is genuinely reading the NSMenu-backed backend.

---

### ⚠️ Correction 1 — `menu_probe` did not accept what its callers hand it

`test_select_options` and `test_toolbar_menu` still failed with
`AttributeError: '_NativeContextMenu' object has no attribute '_items'`.

The probe's docstring says each method takes the backend object, "the
`_context_menu` a widget such as `SelectButton` builds". Measured: that attribute
is the **`ContextMenu` facade**, not the backend —

```
type of _context_menu:            ContextMenu
backend behind it:                _NativeContextMenu
isinstance native (facade):       False        <-- probe took the themed branch
isinstance native (unwrapped):    True
```

So `item_count` fell through to `len(impl._items)`, the facade forwarded `_items`
to the native backend via `__getattr__`, and it raised. Invisible on Windows,
where that same forwarding resolves to the themed backend and works — the exact
"passes on Windows by construction" trap this PR exists to close.

Fixed with a `MenuBackendProbe._unwrap` that all four methods route through, and
the class docstring corrected to say both forms are accepted.

### ⚠️ Correction 2 — the PageStack diagnosis in the body is wrong

The body's step 3 hypothesis (`update_idletasks()` not processing the map event)
is not what was happening. The branch's own precondition assertion —
`assert ... "shown_app did not map the root"` — **never fired**. The root was
mapped. Per the body's own decision tree, that means the pollution is elsewhere.

Bisected, and it is not event-queue state at all. Culprit is
`tests/widgets/public/test_attach_detach.py`, and it is **cumulative** — no single
test triggers it (first 15 pass, 16 fails). Geometry probe, same test, two orders:

```
alone:                root 46x20    pagestack mapped=1  46x20
after attach_detach:  root 94x828   pagestack mapped=0   1x1
                      (body reqheight 1242, 23 slaves)
```

Every earlier test's widgets are still parented to the shared app body. Once their
combined requested height (1242px) exceeds the window (clamped to 828px), the
geometry manager **unmaps whatever no longer fits** — the PageStack, added last.
`winfo_ismapped() == 0` for reasons unrelated to navigation.

Fixed here by marking the module `isolated` so it gets a body it is not sharing.
No test is skipped, so the coverage stays.

The `shown_app` pump change is harmless and arguably reasonable hardening, but it
is not what fixes these two tests, and the body should not be read as saying so.

### 📌 Minor — test count

The body says `test_menu_backend_probe.py` has 10 tests; it has **16** after
98950cdb.

---

### 🔎 Found along the way — filed separately, not fixed here

**The real fix for PageStack is a harness bug, and it is out of scope for this PR.**
`conftest._region()` returns `_region_root`, which on a decorated App **is the
root** — content lands one level deeper in the App's `_content_frame`. So
`_snapshot`/`_reset_scene` see that frame as one permanent child and never look
inside it. **The scene reset has been a no-op for content widgets for the entire
life of the shared-root harness**; every test's widgets pile up all session.

Fixing it makes PageStack pass with no isolation marker and drops the widget leg
from **144s to 80s**. I did not include it, because it exposes two latent bugs:

- **#392** — `Subscription.cancel()` leaves the binding in place and silences every
  other handler on that event. A real product bug; it is why `ThemeToggle` breaks
  once widgets actually get destroyed.
- `test_select_change_event_value_space` picks up 5 change events instead of 1,
  with values from earlier tests. Same trigger file; looks like stale bindtag
  bindings surviving destroy while Tk recycles widget path names. Not chased down.

The harness fix is worth doing once #392 lands, but it turns this PR into a
product-code change, so it should be its own branch.
