### ISSUE TITLE
`v0.1.3` removed `add_validation_rule` from `Select` objects

### ISSUE THREAD

**Issue by bLynnb2762** [israel-dryer/bootstack#356]
### Desktop (please complete the following information):

bootstack version: 0.1.3
OS: Windows

### Describe the bug

In `bootstack 0.1.2` I could use `add_validation_rule` on `Select` widgets. With `0.1.3` I now get an `AttributeError: 'Select' object has no attribute 'add_validation_rule'`. This can be remedied by passing `'required': True` to the `editor_options` in a `FieldItem` object, but doing it this way prevents custom required messages (at least as far as I can tell).

### To Reproduce

My original* code that worked in `0.1.2` (*pared down for simplicity):

```python
import bootstack as bs
from bootstack.dialogs import DialogButton
from bootstack.widgets import Button, Label


with bs.App() as app:
    form = bs.Form(
        title='Form',
        buttons=[
            DialogButton(text='Save', variant='primary', role='primary', icon='floppy', command=lambda _: on_submit()),
        ],
        items=[
            bs.GroupItem(label='Customer Name', col_count=2, items=[
                bs.FieldItem(key='first', label='First'),
                bs.FieldItem(key='last', label='Last'),
            ]),
            bs.GroupItem(label='Mailing Address', col_count=3, columnspan=3, items=[
                bs.FieldItem(key='address', label='Address', columnspan=3),
                bs.FieldItem(key='city', label='City'),
                bs.FieldItem(key='state', label='State', editor='select',
                             editor_options={'values': ['AL', 'AK', 'AZ']}),
                bs.FieldItem(key='zip', label='Zipcode'),
            ]),
        ],
    )

    #########################################
    # Add validation rules to the form fields
    #########################################
    required_fields = {
        'first': 'First Name',
        'last': 'Last Name',
        'state': 'State',
    }
    for field, label in required_fields.items():
        form.field(field).add_validation_rule(
            'required', message=f'{label} is required', trigger='blur'
        )

def on_submit():
    if form.validate():
        print('Form is valid!')

app.run()
```

The way around it:
```python
import bootstack as bs
from bootstack.dialogs import DialogButton
from bootstack.widgets import Button, Label


with bs.App() as app:
    form = bs.Form(
        title='Form',
        buttons=[
            DialogButton(text='Save', variant='primary', role='primary', icon='floppy', command=lambda _: on_submit()),
        ],
        items=[
            bs.GroupItem(label='Customer Name', col_count=2, items=[
                bs.FieldItem(key='first', label='First'),
                bs.FieldItem(key='last', label='Last'),
            ]),
            bs.GroupItem(label='Mailing Address', col_count=3, columnspan=3, items=[
                bs.FieldItem(key='address', label='Address', columnspan=3),
                bs.FieldItem(key='city', label='City'),
                bs.FieldItem(key='state', label='State', editor='select',
                             editor_options={'values': ['AL', 'AK', 'AZ'], 'required': True}),  # Add requirement here
                bs.FieldItem(key='zip', label='Zipcode'),
            ]),
        ],
    )

    #########################################
    # Add validation rules to the form fields
    #########################################
    required_fields = {
        'first': 'First Name',
        'last': 'Last Name',
        # 'state': 'State',  # Remove requirement here
    }
    for field, label in required_fields.items():
        form.field(field).add_validation_rule(
            'required', message=f'{label} is required', trigger='blur'
        )

def on_submit():
    if form.validate():
        print('Form is valid!')

app.run()
```

### Expected behavior

Allowing `add_validation_rule` to apply to `Select` (and other) widgets keeps consistency between behaviors

**Comment by israel-dryer** [comment]
Thanks for the clear report and repro — that made this quick to pin down.

**Root cause.** In `0.1.2`, `form.field('state')` returned the *internal* `SelectBox`, which subclasses the internal `Field` composite and so inherited `add_validation_rule`. In `0.1.3`, [PR #354](https://github.com/israel-dryer/bootstack/pull/354) reworked `Form` to build the **public wrapper** widgets (`bs.Select`, `bs.TextField`, …) so that `editor_options` accept the public keyword names (`step`, `show_border`, `mask`, …) instead of internal Tk options — a deliberate, good change — and `field()` now returns that public wrapper.

The catch: the field-family wrappers (`TextField`, `NumberField`, `DateField`, …) carry `add_validation_rule` via a shared field mixin, so for them the swap was transparent. But `bs.Select` had no such method of its own, and among the non-field editors its internal impl was the only one that had been inheriting it. So `form.field('<select field>')` was the single case that lost the method → `AttributeError`. That's also why the workaround you found (`editor_options={'required': True}`) worked but couldn't carry a custom message — it takes a different path.

**Fix.** [PR #357](https://github.com/israel-dryer/bootstack/pull/357) restores `add_validation_rule` on `bs.Select`, with the same signature as the field family, so your original `0.1.2` code works again — including the custom `message=` and `trigger=`:

```python
form.field('state').add_validation_rule('required', message='State is required', trigger='blur')
```

Merged to `main`; it'll go out in the next `0.1.x` patch release. A regression test now covers exactly this path so it can't silently drop again.

**Comment by israel-dryer** [comment]
This is now fixed and released in **bootstack 0.1.4** (on PyPI). Upgrade with:

```
pip install -U bootstack
```

Your original `0.1.2` code — `form.field(key).add_validation_rule('required', message=..., trigger='blur')` — works again, including the custom message. Thanks again for the clear repro. Closing; please reopen if anything's still off.
