### ISSUE TITLE
test: six macOS test failures are test defects — backend assumptions + order dependence

### ISSUE THREAD

**Issue by israel-dryer** [israel-dryer/bootstack#379]
## Summary

`python tests/run_gui.py` reports six failures on macOS on a clean `main`. All six
are **test defects, not product bugs** — verified individually. They have been
carried as a hand-maintained "known failing" list in `CLAUDE.md`, which is fragile:
telling a real regression from the accepted noise currently requires diffing
against a prose list in a doc.

Not caused by the 0.1.8 scaling fix — the set is identical before and after.

## Category 1 — assume the Win/Linux menu backend (4 tests)

macOS uses `_NativeContextMenu`; these poke at `_ToplevelContextMenu` internals:

| test | error |
|---|---|
| `test_overlay_container_coverage.py::test_propagate_skips_nested_toplevels` | `AttributeError: '_NativeContextMenu' object has no attribute '_toplevel'` |
| `test_toolbar_menu.py::test_add_menu_builds_model_and_trigger` | `AttributeError: '_NativeContextMenu' object has no attribute '_items'` |
| `test_select_options.py::test_selectbutton_disabled_menu_item` | `IndexError: list index out of range` |
| `test_add_toolbar.py::test_bridge_inactive_on_non_macos` | asserts `not app._menus_are_native()` |

The last is self-documenting: it is named `_non_macos`, asserts non-macOS
behavior, and has no skip guard, so it runs on macOS and fails by construction.

**These are also a coverage hole, not just noise.** They are the only tests for
menu construction and overlay propagation, and on macOS they abort before
asserting anything meaningful — so the macOS native-menu path is effectively
untested while appearing tested.

Fix: guard or parametrize by backend so each platform asserts the right thing,
rather than skipping on macOS (a skip would preserve the coverage hole).

## Category 2 — order-dependent (2 tests)

- `test_pagestack.py::test_visited_pages_stay_mapped_on_macos`
- `test_pagestack.py::test_return_after_many_visits_does_not_remap_on_macos`

Both **pass in isolation** (`4 passed` for the file) and fail only in the full
shared-root run. State pollution from an earlier test. Needs the polluting test
identified and the leaked state reset in a fixture.

## Why this is worth clearing

A permanently red baseline is how the recent Tk 9 bugs stayed invisible. Verifying
the 0.1.8 fix required diffing the failure set against the prose list in
`CLAUDE.md` to establish "no regressions" — that works only while the list stays
accurate and someone remembers to check it. A seventh failure would blend in.

See also #378 (the suite cannot complete at all under Tk 9) and #380 (no CI test
workflow), which compound this: nothing is watching automatically.

## Reproduce

```
python tests/run_gui.py          # macOS; 6 failures
python -m pytest tests/widgets/public/test_pagestack.py -q   # 4 passed — order-dependent
```
